# Generated by Django 4.2.9 on 2024-01-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiarySavetable",
            fields=[
                (
                    "diary_uuid",
                    models.IntegerField(
                        db_column="Diary_uuid", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=45)),
                (
                    "diary_title",
                    models.CharField(db_column="Diary_title", max_length=45),
                ),
                ("diary_content", models.TextField(db_column="Diary_content")),
                (
                    "diary_address",
                    models.CharField(
                        blank=True, db_column="Diary_Address", max_length=45, null=True
                    ),
                ),
                (
                    "diary_date",
                    models.DateField(blank=True, db_column="Diary_date", null=True),
                ),
            ],
            options={"db_table": "diary_savetable", "managed": False,},
        ),
    ]
