# Generated by Django 4.2.9 on 2024-01-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myDiary_Backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usertable",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
            ],
            options={"db_table": "usertable", "managed": False,},
        ),
    ]
